bool CheckReady(bool TownCheck, bool CheckCasting);
LPUNITANY FindMercUnit(LPUNITANY pOwner);
LPROSTERUNIT FindPartyById(DWORD dwUnitId);
int GetRelation(UnitAny* unit);
bool IsValidMonster(UnitAny* pUnit);
char* PlayerClass(DWORD ClassId, bool Short);
UnitAny* FindUnit();
LPROSTERUNIT FindPartyByName(LPSTR szName);
POINT GetUnitLocation(bool bHammer);
LPLEVEL GetUnitLevel(LPUNITANY pUnit);
//LPPRESETUNIT FindPresetUnit(DWORD dwClassId, DWORD dwType, LPROOM2 *pRoom);